### ISSUE TITLE
Scala 3 tracking Issue

### ISSUE THREAD

**Issue by Odomontois** [tofu-tf/tofu#1068]
- [ ] Migration of higher-kind core
- [ ] Migration of kernel
- [ ] Migration of higher-kind macros
- [ ] Migration of ce2 support
- [ ] Migration of ce3 support
- [ ] Migration of ZIO support
- [ ] Migration of logging

**Comment by Roman-Statsura** [comment]
I'll take on task for migration zio-logging on Scala 3, if no one minds

**Comment by dos65** [comment]
Attaching the curent status of having Scala3 support for each module :
- [ ] concurrentCE2
- [ ] config
- [x] coreCE2
- [x] coreCE3
- [ ] doobie
- [ ] doobieCE3
- [ ] doobieLogging
- [ ] doobieLoggingCE3
- [ ] env
- [ ] fs2CE2Interop
- [x] fs2CE3Interop
- [x] higherKindCore
- [x] kernel
- [x] kernelCatsMtlInterop
- [x] logging
- [x] loggingDer
- [x] loggingEnumeratum
- [x] loggingLayout
- [x] loggingLog4Cats
- [ ] loggingLog4CatsLegacy
- [x] loggingLogstashLogback
- [x] loggingRefined
- [ ] loggingShapeless
- [x] loggingStr
- [ ] memo
- [ ] observable
- [x] streams
- [ ] zio1Core
- [ ] zio1Interop
- [ ] zio1Logging
- [ ] zio2Core
- [x] zio2Logging
