### ISSUE TITLE
Checklist for cats effect 3 interop

### ISSUE THREAD

**Issue by Odomontois** [tofu-tf/tofu#538]
Here is the list of things that need to be done, related to before  #536 cats effect 3 will become a full member of tofu family

Please add your things in the comments, so I could update the list

- [x] Rework UnliftIO
- [x] Implement CE3 interop 
- [x] Alienating cats-effect 2 from the core modules
- [x] (Optional) seamless, i.e. searchable without imports instances for interop techonogies  (try https://blog.7mind.io/no-more-orphans.html ?)| 
   -  #678
   - #681 
   - #709
- [x] Remove Fiber from the core, think about own abstraction for that, or make Daemon the central abstraction
- [x] Own typeclass for Timer, since [`Timer` now coupled with Concurrent](https://github.com/typelevel/cats-effect/blob/series/3.x/kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala), consider name `Sleep`
- [x] Own typeclass for delaying short effectful non-throwing methods, instead of Sync, consider name `Delay`, this would be also applicable for zio.UIO, URIO

**Comment by Z1kkurat** [comment]
A couple of thoughts on alienating cats-effect 2:
- there are some interfaces that expose APIs based on CE classes - for example `Start` which uses `Fiber` as well as the aforementioned `tofu.syntax.timer`. We have some options for dealing with that: 
  - moving them into separate modules (say, `core-ce2` and `core-ce3`), but it defects the purpose of `core` being an interface module with different instances for different CE versions in corresponding modules
  - making our own `Fiber` interface copying methods from CE2 and implementing that in corresponding modules (but then CE3 may bring new definitions of `Fiber` methods so we will lose some of the functionality in our interface since we won't be able to implement them for CE2)
  - use our own primitives (`Daemon` for example), but it's not in the `core` module - probably it's worth moving `Fire`/`Start`/`Race` to `concurrent` module since these type classes are about concurrency too. This will allow us to alienate CE more easily but can be a pain for some of the users who will need to pull `concurrent` dependency too. Also, the current `Daemon` implementation extends `Fiber` so won't be able to have an interface `concurrent` module and implementation `concurrent-ce2` and `concurrent-ce3` ones. We could un-extend `Daemon` from `Fiber` (which is a breaking change) or make two modules (`concurrent-ce2` and `concurrent-ce3`) with each of them having their own definitions of `Daemon`/`Fire`/`Race`/`Start` based on the corresponding CE interface (this can be a large burden for maintanence)
- there are lots of other modules depending on CE - memo, concurrent, logging, env. We could make modules like "module-ce2" and "module-ce3" or leave the current "module" defaulting to CE2 and "module-ce3" using CE3

@Odomontois @catostrophe @oskin1 WDYT?

**Comment by Z1kkurat** [comment]
We could also think of a user perspective regarding depending on tofu:
- depending on interface module `X` and implementation module `X-ce2` or `X-ce3` (requires separating all interfaces in `X` from all CE-specific APIs)
- depending on module `X` with CE2 implementation or `X-ce3` with CE3 one. This will require duplicating typeclasses, they may differ in the functionality (i.e. `Fiber` with new methods) and it's a large maintenance pain

**Comment by Odomontois** [comment]
@Z1kkurat I don't feel we are going to keep `Fiber` in the core anymore.
It definitely looks like we need to unextend Daemon from Fiber and remove Fiber-related API from the core, leaving only own types

**Comment by catostrophe** [comment]
Let's just drop CE2 support and switch to CE3 in the new version, say 0.11.0. And keep 0.10.x for hotfixes related to CE2.

**Comment by Z1kkurat** [comment]
As a result of the discussion with the maintainers, the following approach will be taken:
- a separate branch will be created
- all efforts towards migration will be performed in this separate branch which will be published as snapshots to try for early adopters
- the migration will be performed by duplicating a module's code to a new module with some suffix (say, `core3`) and adapting it for usage with CE3
- all PRs for migration of a particular module should be made to this separate branch
- once all modules are done, a separate PR to the main branch will be made, which will include removing current modules, renaming the new ones so they replace current ones, and bumping the version along with publishing
- all new functionality should be implemented for a stable CE2 version with (optional) forward-porting to the separate branch
- once a new major version is published, the previous CE2 branch remains in an active support with bugfixes and back-porting of a new functionality for some period of time

Example:
- a branch `ce3-migration` is created
- `core` module is copied to a new module `core3`, adapted to CE3 and merged to this branch
- `optics` module is copied to a new module `optics3` with dependendcy on `core3`, adapted to CE3 and merged to this branch
- the same for all other modules
- when all is done, all modules are dropped, `core3` is renamed to `core`, `optics3` to `optics`, etc. `ce3-migration` is merged to `master` and is now the main development branch

Please feel free to correct/suggest ideas.
